language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.* DOCTRINE_ORM_VERSION=2.4.* DOCTRINE_BUNDLE_VERSION=1.2.*
  - SYMFONY_VERSION=2.5.* DOCTRINE_ORM_VERSION=2.4.* DOCTRINE_BUNDLE_VERSION=1.2.*
  - SYMFONY_VERSION=2.6.* DOCTRINE_ORM_VERSION=2.4.* DOCTRINE_BUNDLE_VERSION=1.2.*

before_script:
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer require doctrine/doctrine-bundle:${DOCTRINE_BUNDLE_VERSION} --no-update
  - composer require doctrine/orm:${DOCTRINE_ORM_VERSION} --no-update
  - composer require doctrine/data-fixtures:1.0.* --no-update
  - composer require twig/twig:1.15.* --no-update
  - composer update --dev

script: phpunit
